
import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';
import { AppNotification, NotificationType, NotificationSettings } from '../types';
import { supabase } from '../lib/supabase';
import { useAuth } from './AuthContext';

const LOCAL_NOTIF_KEY = 'padelpro_notifications_v1';
const LOCAL_SETTINGS_KEY = 'padelpro_notif_settings_v1';

interface NotificationContextType {
    notifications: AppNotification[];
    unreadCount: number;
    settings: NotificationSettings;
    addNotification: (userId: string, type: NotificationType, title: string, message: string, link?: string, meta?: any) => Promise<void>;
    markAsRead: (id: string) => Promise<void>;
    markAllAsRead: () => Promise<void>;
    deleteNotification: (id: string) => Promise<void>;
    updateSettings: (newSettings: Partial<NotificationSettings>) => void;
}

const defaultSettings: NotificationSettings = {
    invites: true,
    matchStart: true,
    results: true,
    system: true
};

const NotificationContext = createContext<NotificationContextType>({
    notifications: [],
    unreadCount: 0,
    settings: defaultSettings,
    addNotification: async () => {},
    markAsRead: async () => {},
    markAllAsRead: async () => {},
    deleteNotification: async () => {},
    updateSettings: () => {},
});

export const NotificationProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const { user, isOfflineMode } = useAuth();
    const [notifications, setNotifications] = useState<AppNotification[]>([]);
    const [settings, setSettings] = useState<NotificationSettings>(defaultSettings);

    // Identify current user/player context
    // This logic ensures we don't lose context. 
    // If logged in as User -> Use User.id. 
    // If Admin viewing as Player -> Use padel_sim_player_id.
    const getCurrentRecipientId = useCallback(() => {
        if (user) return user.id; 
        return localStorage.getItem('padel_sim_player_id') || 'guest';
    }, [user]);

    // Load Settings
    useEffect(() => {
        const stored = localStorage.getItem(LOCAL_SETTINGS_KEY);
        if (stored) setSettings(JSON.parse(stored));
    }, []);

    // Load Notifications
    const loadNotifications = useCallback(async () => {
        const recipientId = getCurrentRecipientId();
        
        // PRIORITIZE ONLINE LOAD IF USER EXISTS, EVEN IF 'isOfflineMode' FLAG SAYS TRUE (HANDLING FLICKER)
        const canUseSupabase = !!user && !isOfflineMode;

        if (!canUseSupabase) {
            // Local Mode
            const stored = localStorage.getItem(LOCAL_NOTIF_KEY);
            if (stored) {
                const all: AppNotification[] = JSON.parse(stored);
                // Filter for current user context strictly
                const mine = all.filter(n => n.userId === recipientId);
                setNotifications(mine.sort((a,b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()));
            } else {
                setNotifications([]);
            }
            return;
        }

        // Online Mode
        try {
            const { data, error } = await supabase
                .from('notifications')
                .select('*')
                .eq('user_id', recipientId)
                .order('created_at', { ascending: false });
            
            if (data) {
                const mapped: AppNotification[] = data.map(n => ({
                    id: n.id,
                    userId: n.user_id,
                    type: n.type as NotificationType,
                    title: n.title,
                    message: n.message,
                    link: n.link,
                    read: n.read,
                    createdAt: n.created_at,
                    meta: n.meta
                }));
                setNotifications(mapped);
            }
        } catch (e) {
            console.error("Error loading notifications:", e);
        }
    }, [isOfflineMode, user, getCurrentRecipientId]);

    useEffect(() => {
        loadNotifications();
        // Poll for updates (Supabase realtime is better but polling is safer for now)
        const interval = setInterval(loadNotifications, 5000); 
        return () => clearInterval(interval);
    }, [loadNotifications]);

    // --- ACTIONS ---

    const addNotification = async (userId: string, type: NotificationType, title: string, message: string, link?: string, meta?: any) => {
        const newNotif: AppNotification = {
            id: isOfflineMode ? `local-n-${Date.now()}` : '', // ID generated by DB if online
            userId,
            type,
            title,
            message,
            link,
            read: false,
            createdAt: new Date().toISOString(),
            meta
        };

        const canUseSupabase = !!user && !isOfflineMode; // Same check

        if (!canUseSupabase) {
            const stored = localStorage.getItem(LOCAL_NOTIF_KEY);
            const all: AppNotification[] = stored ? JSON.parse(stored) : [];
            all.push(newNotif);
            localStorage.setItem(LOCAL_NOTIF_KEY, JSON.stringify(all));
            loadNotifications();
        } else {
            await supabase.from('notifications').insert([{
                user_id: userId,
                type,
                title,
                message,
                link,
                read: false,
                meta
            }]);
            // No need to reload manually if polling/realtime works, but safer to do it
            loadNotifications(); 
        }
    };

    const markAsRead = async (id: string) => {
        const canUseSupabase = !!user && !isOfflineMode;

        if (!canUseSupabase) {
            const stored = localStorage.getItem(LOCAL_NOTIF_KEY);
            if (stored) {
                const all: AppNotification[] = JSON.parse(stored);
                const updated = all.map(n => n.id === id ? { ...n, read: true } : n);
                localStorage.setItem(LOCAL_NOTIF_KEY, JSON.stringify(updated));
                loadNotifications();
            }
        } else {
            // Optimistic update for UI snap
            setNotifications(prev => prev.map(n => n.id === id ? { ...n, read: true } : n));
            await supabase.from('notifications').update({ read: true }).eq('id', id);
        }
    };

    const markAllAsRead = async () => {
        const recipientId = getCurrentRecipientId();
        const canUseSupabase = !!user && !isOfflineMode;

        if (!canUseSupabase) {
            const stored = localStorage.getItem(LOCAL_NOTIF_KEY);
            if (stored) {
                const all: AppNotification[] = JSON.parse(stored);
                const updated = all.map(n => n.userId === recipientId ? { ...n, read: true } : n);
                localStorage.setItem(LOCAL_NOTIF_KEY, JSON.stringify(updated));
                loadNotifications();
            }
        } else {
            setNotifications(prev => prev.map(n => ({ ...n, read: true })));
            await supabase.from('notifications').update({ read: true }).eq('user_id', recipientId);
        }
    };

    const deleteNotification = async (id: string) => {
        const canUseSupabase = !!user && !isOfflineMode;

        if (!canUseSupabase) {
            const stored = localStorage.getItem(LOCAL_NOTIF_KEY);
            if (stored) {
                const all: AppNotification[] = JSON.parse(stored);
                const updated = all.filter(n => n.id !== id);
                localStorage.setItem(LOCAL_NOTIF_KEY, JSON.stringify(updated));
                loadNotifications();
            }
        } else {
            setNotifications(prev => prev.filter(n => n.id !== id));
            await supabase.from('notifications').delete().eq('id', id);
        }
    };

    const updateSettings = (newSettings: Partial<NotificationSettings>) => {
        const updated = { ...settings, ...newSettings };
        setSettings(updated);
        localStorage.setItem(LOCAL_SETTINGS_KEY, JSON.stringify(updated));
    };

    const unreadCount = notifications.filter(n => !n.read).length;

    return (
        <NotificationContext.Provider value={{
            notifications,
            unreadCount,
            settings,
            addNotification,
            markAsRead,
            markAllAsRead,
            deleteNotification,
            updateSettings
        }}>
            {children}
        </NotificationContext.Provider>
    );
};

export const useNotifications = () => useContext(NotificationContext);
